---

- hosts: all
  become: true
  tasks:

  - name: install extra packages for enterprise linux
    yum:
      name: epel-release
      state: latest
    when: ansible_os_family == "Rocky"

  - name: update epel-release cache
    yum:
      update_cache=true
    when: ansible_os_family == "Rocky"

  - name: install nginx, tldr and htop packages
    yum:
      name:
        - nginx
        - htop
        - tldr
      state: latest 
    when: ansible_os_family == "Rocky"

