---

- hosts: all
  become: true
  tasks:

  - name: install extra packages for enterprise linux
    package:
      name:
        - epel-release
      state: latest
    when: ansible_os_family == "Rocky"

  - name: update epel-release cache
    package:
      update_cache=true
    when: ansible_os_family == "Rocky"

  - name: install nginx, tldr and htop packages
    package:
      name:
        - htop
        - tldr
      state: latest 
    when: ansible_os_family == "Rocky"

- hosts: keepalive_haproxy
  become: true
  tasks:

  - name: install keepalived and haproxy on [keepalive_haproxy] servers
      package:
        name:
          - keepalived
          - haproxy
        state: latest

- hosts: web_servers
  become: true
  tasks:

  - name: install nginx on [web_servers]
    package:
      name:
        - nginx
    state: latest